### ISSUE TITLE
More unit tests + E2E testing

### ISSUE THREAD

**Issue by benjxia** [cse110-fa22-group25/warrantracker#23]

**Comment by chrisliang12** [comment]
I think your branch benxia/issue23 is not developed based on the main branch, instead, it seems you add those unit tests on top of the modify branch. This is bad because modify branch should not be merged with this issue since it has bugs and unfinished features. So you probably need to create a new branch and add new unit tests in that branch and link that branch to this issue when creating a new pr. @benjxia

**Comment by chrisliang12** [comment]
btw I also add some unit tests for the deletion feature in the branch benjxia/issue23

**Comment by benjxia** [comment]
yea probably just merge the tests into main manually after modify is done

**Comment by benjxia** [comment]
originally wanted to try and get a basic test for modify running but it was harder to do than expected

**Comment by benjxia** [comment]
will need to add lab 8 puppeteer stuff for every feature later
